
os: osx
language: node_js
node_js:
  - "stable"
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  verbose: true
  on:
    branch: master
after_success:
  - npm run deploy
