// User's Personal Profile for viewing and editind
export const ADD_NAME = 'ADD_NAME';
export const ADD_DESC = 'ADD_DESC';
export const ADD_EMAIL = 'ADD_EMAIL';
export const ADD_PHONE = 'ADD_PHONE';
export const ADD_WEBSITE = 'ADD_WEBSITE';
export const ADD_IMAGE = 'ADD_IMAGE';
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILE_TO_USERPROFILES = 'ADD_PROFILE_TO_USERPROFILES';
export const REMOVE_LOCAL_PROFILE = 'REMOVE_LOCAL_PROFILE';

export const UPDATE_PROFILE_NAME_BY_KEY = 'UPDATE_PROFILE_NAME_BY_KEY';
export const UPDATE_PROFILE_WEBSITE_BY_KEY = 'UPDATE_PROFILE_WEBSITE_BY_KEY';
export const UPDATE_PROFILE_PHONE_BY_KEY = 'UPDATE_PROFILE_PHONE_BY_KEY';
export const UPDATE_PROFILE_DESC_BY_KEY = 'UPDATE_PROFILE_DESC_BY_KEY';
export const UPDATE_PROFILE_EMAIL_BY_KEY = 'UPDATE_PROFILE_EMAIL_BY_KEY';
export const UPDATE_PROFILE_IMAGE_BY_KEY = 'UPDATE_PROFILE_IMAGE_BY_KEY';
// DB interactive
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const ADD_PROFILE_REQUEST = 'ADD_PROFILE_REQUEST';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST';
export const DELETE_PROFILE_FAILURE = 'DELETE_PROFILE_FAILURE';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';

// DB interactive
export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';

// Event
export const ADD_EVENT_NAME = 'ADD_EVENT_NAME';
export const ADD_EVENT_DATE = 'ADD_EVENT_DATE';
export const ADD_EVENT_TIME = 'ADD_EVENT_TIME';
export const ADD_EVENT_DESC = 'ADD_EVENT_DESC';
export const ADD_EVENT_EMAIL = 'ADD_EVENT_EMAIL';
export const ADD_EVENT_PHONE = 'ADD_EVENT_PHONE';
export const ADD_EVENT_WEBSITE = 'ADD_EVENT_WEBSITE';
export const ADD_EVENT_IMAGE = 'ADD_EVENT_IMAGE';
export const ADD_EVENTS_TO_USEREVENTS = 'ADD_EVENTS_TO_USEREVENTS';
export const REMOVE_LOCAL_EVENT = 'REMOVE_LOCAL_EVENT';

export const UPDATE_EVENT_NAME_BY_KEY = 'UPDATE_EVENT_NAME_BY_KEY';
export const UPDATE_EVENT_WEBSITE_BY_KEY = 'UPDATE_EVENT_WEBSITE_BY_KEY';
export const UPDATE_EVENT_PHONE_BY_KEY = 'UPDATE_EVENT_PHONE_BY_KEY';
export const UPDATE_EVENT_EMAIL_BY_KEY = 'UPDATE_EVENT_EMAIL_BY_KEY';
export const UPDATE_EVENT_IMAGE_BY_KEY = 'UPDATE_EVENT_IMAGE_BY_KEY';
export const UPDATE_EVENT_LOCATION_BY_KEY = 'UPDATE_EVENT_LOCATION_BY_KEY';
export const UPDATE_EVENT_CALENDAR_BY_KEY = 'UPDATE_EVENT_CALENDAR_BY_KEY';

// Authentication
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';


export const GOOGLE_SERVERAUTHCODE_RECEIVED = 'GOOGLE_SERVERAUTHCODE_RECEIVED';
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS';
export const GOOGLE_SIGNOUT = 'GOOGLE_SIGNOUT';
export const GOOGLE_SIGNIN_REQUEST = 'GOOGLE_SIGNIN_REQUEST';

export const INTERNET_CONNECTIVITY_CHANGED_DETECTED = "INTERNET_CONNECTIVITY_CHANGED_DETECTED";

export const DB_CLIENT_INITIALIZED = 'DB_CLIENT_INITIALIZED';
export const DB_CLIENT_ALREADY_INITIALIZED = 'DB_CLIENT_ALREADY_INITIALIZED';
