# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'Tamari' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  
  # Pods for Tamari
    pod 'DoubleConversion'
    pod 'glog'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'GoogleSignIn'
  

#pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTSettings',
    'RCTAnimation',
    'RCTLinkingIOS',
    # Add any other subspecs you want to use in your project
    # Remove any subspecs you don't want to use in your project
  ]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'react-native-webview', :path => '../node_modules/react-native-webview'
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
    #pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
#pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
#pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  end
